files:
  - source: /UA-UK/*.php
    translation: /%locale%%two_letters_code%.%original_file_name%
    
    files:
  - source: /en-US/*.php
    translation: /%locale%/%two_letters_code%.%file_extension%
