files:
  - source: /UA-UK/*.php
    translation: /%locale%/%file_name%.%two_letters_code%.%file_extension%
    
    files:
  - source: /en-US/*.php
    translation: /%locale%/%file_name%.%two_letters_code%.%file_extension%
